### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by hookenz** [JohanSamyn/gohg#2]
I'd like to use this for an in house build system.  

The project here and on bitbucket appears to be dead?  any plans to revive it?

**Comment by JohanSamyn** [comment]
Hi Matt,
No plans to reive. But feel free to use what you like.
cheers, Johan

-- 
________________________________________________________________________
"Perfection seems to be achieved, not when there is nothing more to add,
but when there is nothing left to take away." - A. de Saint-Exupéry
"Simplicity is the ultimate sophistication." - Leonardo da Vinci
